---
# handlers file for roles/boot-server
- name: svc_dnsmasq
  become: true
  service:
    name: dnsmasq
    enabled: yes
    state: restarted

- name: svc_firewalld
  become: true
  service:
    name: firewalld
    state: restarted
