---
##
## This includes all tasks, and is a bit messy
## Will split the tasks in separate files in the future,
## and add proper descriptions
##
- name: RedHat | install packages
  become: true
  yum:
    name: "{{ item }}"
    state: present
  loop: "{{ software }}"

- name: RedHat | create root folder
  become: true
  file:
    path: /var/lib/tftpboot
    state: directory
    owner: nobody
    group: nobody
    mode: 0777

- name: RedHat | create pxeboot folder
  become: true
  file:
    path: /var/lib/tftpboot/pxelinux.cfg
    state: directory
    owner: nobody
    group: nobody
    mode: 0777

- name: RedHat | copy dnsmasq template
  become: true
  template:
    src: dnsmasq.conf.j2
    dest: /etc/dnsmasq.conf
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify: svc_dnsmasq

- name: RedHat | copy idefault menu template
  become: true
  template:
    src: default.j2
    dest: /var/lib/tftpboot/pxelinux.cfg/default
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify: svc_dnsmasq

- name: RedHat | link to pxelinux files
  become: true
  file:
    src: /usr/share/syslinux/pxelinux.0
    dest: /var/lib/tftpboot/pxelinux.0
    state: link

- name: RedHat | download ipxe bootfiles
  become: true
  get_url:
    url: "http://boot.ipxe.org/{{ item }}"
    dest: "/var/lib/tftpboot/{{ item }}"
  loop:
  - ipxe.efi
  - undionly.kpxe
  - ipxe.lkrn

- name: RedHat | pxe firewall services
  become: true
  firewalld:
    service: "{{ item }}"
    permanent: true
    state: enabled
  loop:
  - dhcp
  - tftp

- name: RedHat | ipxe firewall ports
  become: true
  firewalld:
    port: "{{ item }}/tcp"
    permanent: true
    state: enabled
  loop:
  - 8080
  - 8081

- meta: flush_handlers
