---
##
## Install required packages
## These are defined in "defaults/main.yml"
## under the "software" list
##
- name: RedHat | install packages
  become: true
  yum:
    name: "{{ item }}"
    state: present
  loop: "{{ software }}"
